[http]
  [http.routers]
    [http.routers.portainer]
      entryPoints = ["web"]
      service = "portainer"
      rule = "Host(`portainer.crimsonlabs.be`)"
  [http.routers]
    [http.routers.guacamole]
      entryPoints = ["web"]
      service = "guacamole"
      rule = "Host(`guacamole.crimsonlabs.be`)"
  [http.services]
    [http.services.portainer]
      [http.services.portainer.loadBalancer]
        passHostHeader = true
        [[http.services.portainer.loadBalancer.servers]]
          url = "http://10.0.0.6:9000"
          [http.services.portainer]
    [http.services.guacamole.loadBalancer]
      passHostHeader = true
      [[http.services.guacamole.loadBalancer.servers]]
        url = "http://10.0.0.6:8080"
